name: chart_data_table
description: Chart Data Table module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  charts_flutter: ^0.12.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic:

flutter:
  uses-material-design: true
  assets:
    - assets/quarterly_result.json

  module:
    androidX: true
    androidPackage: com.example.chart_data_table
    iosBundleIdentifier: com.example.chartDataTable
