name: neumorphism_design
description: Neumorphism Design module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_neumorphic: ^3.1.0
  flutter_colorpicker: ^0.4.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Samsung
      fonts:
        - asset: fonts/SamsungSans-Bold.ttf
        
  module:
    androidX: true
    androidPackage: com.example.neumorphism_design
    iosBundleIdentifier: com.example.neumorphismDesign
