name: stock_chart
description: Stock Chart module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_k_chart: ^0.2.0
  http: ^0.13.4
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic:

flutter:
  uses-material-design: true
  assets:
    - assets/depth.json

  module:
    androidX: true
    androidPackage: com.example.stock_chart
    iosBundleIdentifier: com.example.stockChart
