name: material_design_showcase
description: Material Design Showcase module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_material_showcase: 
    path: ../flutter_material_showcase
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.material_design_showcase
    iosBundleIdentifier: com.example.materialDesignShowcase
