name: settings_ui_showcase
description: Settings Ui Showcase module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  settings_ui: ^1.0.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic:

flutter:
  uses-material-design: true
  assets:
      - assets/settings.png
      
  module:
    androidX: true
    androidPackage: com.fluwix.settings_ui_showcase
    iosBundleIdentifier: com.fluwix.settingsUiShowcase
