name: animated_icons
description: Animated Icons module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_icons: ^1.0.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  pedantic:

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.animated_icons
    iosBundleIdentifier: com.example.animatedIcons
