name: shimmer_effect
description: Shimmer Effect module.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shimmer: ^3.0.0
  common_ui:
    path: ../common_ui
  showcase_view:
    path: ../showcase_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/chevron_right.png
    - assets/background.jpg

  module:
    androidX: true
    androidPackage: com.example.shimmer_effect
    iosBundleIdentifier: com.example.shimmerEffect
